### ISSUE TITLE
Bug when changing "leverage used"

### ISSUE THREAD

**Issue by SeanBannister** [louters/Margin_trading#1]
Hi, I noticed a bug when I change "leverage used" to 2. It seems to output the wrong margin call details. Sorry I haven't had a chance to fix this.

![image](https://cloud.githubusercontent.com/assets/197231/26107546/032a833a-3a8d-11e7-8d3b-3f9f66b8c1e4.png)

**Comment by SeanBannister** [comment]
@louters maybe I don't understand leverage, is this correct?

**Comment by louters** [comment]
There is no issue with the spreadsheet from what I see. The problem is that you say: buy 5 ETH at 100 USD when you have 100 USD on your account. Basically that means for any level of leverage below 5 (1/5* 500 = 100) you would not be able to put that trade because you do not have the margin available to secure the trade.
Short answer: if you don't understand what I have written above, you do not understand leverage. Go read the examples and explanations on Kraken (as many times you need to figure this out). I have spent a lot of time trying to help people with this and have not received much appreciation.
